// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
// import axios from "axios";
import ClientProvider from "@/providers/ClientProvider";
// export const metadata: Metadata = {
//   title: "IDINTECH",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/idintech.png",
//     shortcut: "/images/idintech.png",
//     apple: "/images/idintech.png",
//   },
// };

// export async function generateMetadata(): Promise<Metadata> {
//   // read route params
//   // const id = params.id;

//   // // fetch data
//   // const product = await fetch(`https://.../${id}`).then((res) => res.json());

//   // // optionally access and extend (rather than replace) parent metadata
//   // const previousImages = (await parent).openGraph?.images || [];
//   const fetchContact = async () => {
//     const { data } = await axios.get(
//       `${process.env.NEXT_PUBLIC_BACKEND_URL}contact`
//     );
//     return data;
//   };
//   const contact = await fetchContact();
//   return {
//     title: contact.companyName,
//     icons: {
//       icon: contact.logoUrl,
//     },
//   };
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientProvider>
          <Header />
        </ClientProvider>
        {children}
        <ClientProvider>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
